name: "Build android"

on: push

jobs:
  build_android:
    runs-on: ubuntu-latest

    steps:
      # Setup Java environment in order to build the Android app.
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Build Android
        run: |
          flutter pub run build_runner build --delete-conflicting-outputs
          flutter clean
          flutter pub get
          flutter build apk
