name: "Label issues"

on:
  issues:
    types:
      - opened

jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Label issues
        uses: andymckay/labeler@master
        with:
          # Просто добавляет плашку
          add-labels: "new issues"
          repo-token: ${{ secrets.SECRET_ISSUES }}
