include: package:surf_lint_rules/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: true

analyzer:
  exclude:
    - lib/**/*.g.dart
    - lib/**/*.gr.dart
    - lib/assets/**
    - tools/bricks/**/__brick__/**

