useNewNullableDeterminationStrategy: true

templates:
  - type: model
    fileExtension: dart
    nameSuffix: Dto
    fileNameCase: snakeCase
    templatePath: templates/retrofit_model.stencil
    destinationPath: ../../lib/api/data
  - type: enum
    fileExtension: dart
    nameSuffix: Dto
    fileNameCase: snakeCase
    templatePath: templates/retrofit_enum.stencil
    destinationPath: ../../lib/api/data